### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by gabrieldarezzo** [Kauanphbbb/JogoDaVelhaJS#1]
Primeiramente parabéns!
Ficou bem massa seu jogo da velha. (tanto IA, CSS) 

Já pensou em deixar uma Demo? (Link acessível para demonstração) 
Levando em conta q é só HTML/CSS/JS é bem legal essa possibilidade.

Da uma bizu nesse cara:
https://docs.github.com/pt/free-pro-team@latest/github/working-with-github-pages/creating-a-github-pages-site

Assim literalmente ele fica testável com um clique ;) 

Exemplo de um Repo com link / demo / foto
https://github.com/gabrieldarezzo/rpg

**Comment by Kauanphbbb** [comment]
Dei uma olhada e achei muito boa a sugestão, obrigado. Vou ajeitando aqui para que possam ter a demo.

**Comment by Kauanphbbb** [comment]
Coloquei no github pages, mas ainda está dando como página não encontrada. Mais tarde olho novamente para corrigir caso ainda não seja encontrada a página

**Comment by Kauanphbbb** [comment]
Tudo funcionando corretamente, vou apenas colocar algumas fotos no repositório depois
